name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!**/*.mpack'

jobs:
  build:

    runs-on: macos-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: legacy - vstool setup rep-build
      run: /Applications/Visual\ Studio.app/Contents/MacOS/vstool setup rep-build $PWD
      working-directory: legacy
      continue-on-error: true

    - name: beta - vstool setup rep-build
      run: /Applications/Visual\ Studio.app/Contents/MacOS/vstool setup rep-build $PWD
      working-directory: beta
      continue-on-error: true

    - name: stable - vstool setup rep-build
      run: /Applications/Visual\ Studio.app/Contents/MacOS/vstool setup rep-build $PWD
      working-directory: stable
      continue-on-error: true

    - name: Publish Legacy Repo
      uses: actions/upload-artifact@v2
      with:
        name: Legacy
        path: |
          legacy/*.mrep
          legacy/index.html

    - name: Publish Beta Repo
      uses: actions/upload-artifact@v2
      with:
        name: Beta
        path: |
          beta/*.mrep
          beta/index.html

    - name: Publish Stable Repo
      uses: actions/upload-artifact@v2
      with:
        name: Stable
        path: |
          stable/*.mrep
          stable/index.html
